### PR TITLE
cleanup a few broken bits

### PR DESCRIPTION
**Pull request by fiendish**
The biggest issue is:
Sometimes the metocean server sends error 500 when preparing init.
(Actually not just when preparing init. It sends errors 500/502 sometimes
when handling tile requests too.) These errors are transient, so additional
calls rectify the miss. We need to actually check for valid code after fetching it
and optionally try again. An additional callback is fired after fetching the init 
call. Done with jquery.getScript because adding "onload" to the original wasn't
working for me.

Other things should be obvious.

### CODE REVIEW

**Comment by tcoats** [comment]
Brilliant work - thank you!

Any chance we can lose the jQuery dependency by using [something like this](http://stackoverflow.com/a/28002292/144207)?

```js
function getScript(source, callback) {
    var script = document.createElement('script');
    var prior = document.getElementsByTagName('script')[0];
    script.async = 1;
    prior.parentNode.insertBefore(script, prior);

    script.onload = script.onreadystatechange = function(_, isAbort) {
        if (isAbort || !script.readyState || script.readyState == 'loaded' || script.readyState == 'complete') {
            script.onload = script.onreadystatechange = null;
            script = undefined;

            if (!isAbort && callback) callback();
        }
    };

    script.src = source;
}
```

I don't know how good the above code is, and it adds a bit of extra baggage, but is probably worth it for framework independence. Thoughts?

**Comment by fiendish** [comment]
You're right about preserving framework independence. Added to the PR.

**Comment by tcoats** [comment]
Excellent, thank you for the fixes!

**Comment by tcoats** [comment]
Merged and released, cheers for the fixes!

**Pull request merged**
